from app.emailer import send_email_with_attachment
from app.llm import route_query, write_sales_answer
from app.models import AgentRequest, AgentResponse, Route
from app.reporting import create_sales_pdf
from app.sales_repository import fetch_sales_rows, summarize_sales
import re


class RouterAgent:
    def route(self, query: str) -> Route:
        return route_query(query)


class SupabaseSalesAgent:
    def run(self, query: str) -> AgentResponse:
        rows = fetch_sales_rows(query)
        summary = summarize_sales(rows)
        answer = write_sales_answer(query, summary.model_dump(mode="json"))
        return AgentResponse(route=Route.query_sales, answer=answer, data=summary.model_dump(mode="json"))


class EmailReportAgent:
    def run(self, request: AgentRequest) -> AgentResponse:
        rows = fetch_sales_rows(request.query)
        summary = summarize_sales(rows)
        sales_answer = write_sales_answer(request.query, summary.model_dump(mode="json"))
        report_path = create_sales_pdf(summary, request.query)
        recipient = send_email_with_attachment(
            subject="Ecommerce Sales Report",
            body=f"Attached is the ecommerce sales report generated by the sales agent.\n\n{sales_answer}",
            attachment_path=report_path,
            recipient=request.recipient or _extract_email(request.query),
        )
        answer = f"{sales_answer}\n\nCreated the sales PDF report and emailed it to {recipient}."
        return AgentResponse(
            route=Route.email_report,
            answer=answer,
            report_path=report_path,
            emailed_to=recipient,
            data=summary.model_dump(mode="json"),
        )


class SalesAgentOrchestrator:
    def __init__(self) -> None:
        self.router = RouterAgent()
        self.sales_agent = SupabaseSalesAgent()
        self.report_agent = EmailReportAgent()

    def run(self, request: AgentRequest) -> AgentResponse:
        route = self.router.route(request.query)
        if route == Route.email_report:
            return self.report_agent.run(request)
        return self.sales_agent.run(request.query)


def _extract_email(text: str) -> str | None:
    match = re.search(r"[\w.+-]+@[\w-]+\.[\w.-]+", text)
    return match.group(0) if match else None
